name: Auto Update ZeroDNS

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if already auto-committed today
        run: bash scripts/skip_if_already_run_today.sh

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run ZeroDNS Filter Automation
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scripts/resolve_domains.py

      - name: Commit and Push (with rebase for conflict prevention)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ZeroDNS.txt
          git commit -m "auto: update ZeroDNS" || exit 0
          git pull --rebase || git fetch origin main && git reset --hard origin/main
          git push
