name: ZeroDNS Automation

on:
  schedule:
    - cron: '0 3 * * *'      # 매일 오전 12시(KST 9시)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PyPy 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.10'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run ZeroDNS
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python src/main.py
